# Generated by Django 2.0 on 2018-01-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180131_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='search_terms',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
