# Generated by Django 2.0 on 2018-02-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='prediction',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
