# Generated by Django 2.0 on 2018-02-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180202_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='moving_average',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
    ]
