export const LOAD_STOCKS_SUCCESS = 'LOAD_STOCKS_SUCCESS';
export const LOAD_STOCKS_ERROR = 'LOAD_STOCKS_SUCCESS';

export const LOAD_STOCK_SUCCESS = 'LOAD_STOCK_SUCCESS';
export const LOAD_STOCK_ERROR = 'LOAD_STOCK_SUCCESS';
